# Hyprland Config

source = /home/savvy/dotfiles/hypr/modules/animations.conf

source = /home/savvy/dotfiles/hypr/modules/defaults.conf

source = /home/savvy/dotfiles/hypr/modules/envVar.conf

source = /home/savvy/dotfiles/hypr/modules/input.conf

source = /home/savvy/dotfiles/hypr/modules/keybinds.conf

source = /home/savvy/dotfiles/hypr/modules/look.conf

source = /home/savvy/dotfiles/hypr/modules/monitor.conf

source = /home/savvy/dotfiles/hypr/modules/permissions.conf

source = /home/savvy/dotfiles/hypr/modules/windowAndWorkspaces.conf



# Auto-Execute at startup

exec-once = /home/savvy/dotfiles/scripts/autoStart.sh
