# Kitty Fonts
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12

# Options
enable_audio_bell no

#  Color

# ANSI colors
color0  #45475a
color1  #f38ba8
color2  #a6e3a1
color3  #f9e2af
color4  #89b4fa
color5  #f5c2e7
color6  #94e2d5
color7  #bac2de

color8  #585b70
color9  #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #f5c2e7
color14 #94e2d5
color15 #cdd6f4

# Other colors
foreground #cdd6f4
background #1a1a1e
cursor     #e0f0ff


background_blur 1
background_opacity 0.8
background_tint 1
dim_opacity 0.90

cursor_shape block
cursor_beam_thickness 2
cursor_blink_interval 1
cursor_trail 2
cursor_trail_length 50
cursor_trail_decay 0.1 0.3

confirm_os_window_close 0
