# Kitty Fonts
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12

# Options
enable_audio_bell no

# Kanagawa Wave

# ANSI colors
color0  #16161D
color1  #C34043
color2  #76946A
color3  #C0A36E
color4  #7E9CD8
color5  #957FB8
color6  #6A9589
color7  #C8C093

color8  #727169
color9  #E82424
color10 #98BB6C
color11 #E6C384
color12 #7FB4CA
color13 #938AA9
color14 #7AA89F
color15 #DCD7BA

# Other colors
foreground #DCD7BA
background #1F1F28
cursor     #DCD7BA

background_opacity 1
background_tint 1

cursor_shape block
cursor_beam_thickness 2
cursor_blink_interval 1
cursor_trail 2
cursor_trail_length 50
cursor_trail_decay 0.1 0.3

confirm_os_window_close 0
