unbind C-b
set -g prefix C-Space
set -g base-index 1
set -g renumber-windows on
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g detach-on-destroy off

# Auto Install
set -g @tpm-install-auto 'on'

# Vim
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "wl-copy"
unbind -T copy-mode-vi MouseDragEnd1Pane

set -g set-clipboard on
set -g mouse on
set -g status-interval 3

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

unbind f
bind-key f display-popup -E "~/dotfiles/apps/tmux/tmux-sessionizer.sh"

# Splits
unbind %
unbind '"'
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Resize
bind -r j resize-pane -D 2
bind -r k resize-pane -U 2
bind -r l resize-pane -R 2
bind -r h resize-pane -L 2
bind -r m resize-pane -Z

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

bind R run-shell "~/.config/tmux/plugins/tpm/bin/install_plugins && tmux source ~/.config/tmux/tmux.conf" \; display "Reloaded!"

# Theme
bg="#1e1e2e"
default_fg="#cdd6f4"
session_fg="#a6e3a1"
active_window_fg="#89dceb"
active_pane_border="#6c7086"

set -g status-style "bg=${bg},fg=${default_fg}"
set -g status-position bottom
set -g status-justify centre
set -g status-left-length 100
set -g status-right-length 100
set -g status-left "#[fg=${session_fg},bold,bg=${bg}]  #S"
set -g status-right "#[fg=#89b4fa,bold] %H:%M #[fg=#6c7086]|#[fg=#cdd6f4] %d %b"
set -g window-status-current-format "#[fg=${active_window_fg},bold,bg=default] #I.#W"
set -g window-status-format "#[fg=${default_fg},bg=default] #I.#W"
set -g window-status-last-style "fg=${default_fg},bg=default"
set -g pane-active-border-style "fg=${active_pane_border},bg=default"
set -g pane-border-style "fg=brightblack,bg=default"
set -g message-style "bg=${bg},fg=${default_fg}"

# auto install tpm if missing
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

# Install plugins and set installed to true
run '~/.config/tmux/plugins/tpm/tpm'
run-shell '~/.config/tmux/plugins/tpm/bin/install_plugins > /tmp/tpm-install.log 2>&1 & true'
